services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: chipz-app-production:latest
    container_name: chipz-app-production
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - chipz-network

networks:
  chipz-network:
    driver: bridge
